version: '3'
services:
  web:
    container_name: wasmgameoflife-web
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./pkg:/usr/share/nginx/html/pkg